on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Once per day at 12:00 AM
    - cron:  '0 0 * * *'

jobs:
  check-broken-links:
    runs-on: ubuntu-22.04
    container: ubuntu:latest
    steps:
      - name: Install wget
        run: apt update && apt install -y -qq wget
      - uses: actions/checkout@v3
      - name: Check ${{ matrix.language }}
        if: always()
        shell: bash
        run: ./check_broken_links.sh https://reunicorn.app
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: /tmp/reunicorn_broken_links.log
